---
kind: pipeline
type: docker
name: go-1-18-test

steps:
- name: test
  image: golang:1.18
  commands:
  - go test ./...

---
kind: pipeline
type: docker
name: go-1-19

volumes:
  - name: deps
    temp: {}

steps:
- name: test
  image: golang:1.19
  volumes:
    - name: deps
      path: /go
  commands:
  - go test ./...

- name: go-cover
  image: golang:1.19
  volumes:
    - name: deps
      path: /go
  commands:
  - go test ./...  -coverpkg=./... -coverprofile ./coverage.out
  - go tool cover -func ./coverage.out

- name: osv-dependency-scan
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
  - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
  - osv-scanner -r ./