---
kind: pipeline
name: go-1-18

steps:
- name: test
  image: golang:1.18
  commands:
  - go test ./...

---
kind: pipeline
name: go-1-19

steps:
- name: test
  image: golang:1.19
  commands:
  - go test ./...

- name: go-cover
  image: golang:1.19
  commands:
  - go test ./...  -coverpkg=./... -coverprofile ./coverage.out
  - go tool cover -func ./coverage.out

---
kind: pipeline
name: osv-dependency-scan

steps:
- name: osv-vuln-dep-scanner
  image: golang
  commands:
  - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
  - osv-scanner -r ./
